### ISSUE TITLE
Back-end integration with firebase realtime database

### ISSUE THREAD

**Issue by enzi077** [enzi077/furry-fiesta#1]
1. List items not being added again at **_WorkerList.js_** to the database once they are removed from **_ProfileList.js_**.
2. After reset password in the component **_SignIn.js_**, the user gets logged in successfully with an alert from firebase, "**Wrong Password**"

**Comment by swapnilsrivastava98** [comment]
For the second point I see no code is present for reset functionality, also error handling section only returns the alert messages, no action is implemented when error is handled. You may add the link to signin page after password is reset or just ensure it doesn't go to submit once password is reset.
There's not much to code,  clearing the pwd field in reset section would be enough

**Comment by swapnilsrivastava98** [comment]
For first point i would say store the removed data is a temp list, and validate whether the list items are present in workerList(sort of double check) and if not present, then go ahead and add them from temp list to workerList.

**Comment by enzi077** [comment]
> For first point i would say store the removed data is a temp list, and validate whether the list items are present in workerList(sort of double check) and if not present, then go ahead and add them from temp list to workerList.

This is being done in the react state. So no issue in the front end. It's the backend firebase which is not allowing removed stuff to be added once again.

**Comment by enzi077** [comment]
> For the second point I see no code is present for reset functionality, also error handling section only returns the alert messages, no action is implemented when error is handled. You may add the link to signin page after password is reset or just ensure it doesn't go to submit once password is reset.
> There's not much to code, clearing the pwd field in reset section would be enough

If you go over the SignIn.js component there is indeed an onclick listener on "Forgot password". The listener fires up a Firebase function named sendResetPasswordEmail or the likes of it, which when triggered sends an email with password reset. Now, when the user resets the password and signs in once again, he or she gets signed in but with the alert error. I believe it's a synchronisation issue of firebase and ReactJS. Do fork it and try it out locally with your own dummy firebase data, deploy and then try.

**Comment by enzi077** [comment]
Issue resolved
